"""
config/skill_taxonomy.py
────────────────────────
Canonical dictionary of 200+ technical skills, grouped by domain.

Structure
─────────
SKILL_TAXONOMY: dict[str, list[str]]
    key   → canonical skill name (lowercase, used throughout the pipeline)
    value → list of known aliases / abbreviations for that skill

The extraction layer uses this taxonomy for both exact and fuzzy matching.
"""

from __future__ import annotations

SKILL_TAXONOMY: dict[str, list[str]] = {
    # ── Programming Languages ────────────────────────────────
    "python": ["python3", "python 3", "py"],
    "javascript": ["js", "javascript es6", "es2015", "ecmascript"],
    "typescript": ["ts", "typescript 5"],
    "java": ["java 17", "java 21", "jdk"],
    "c#": ["csharp", "c sharp", "dotnet c#"],
    "c++": ["cpp", "c plus plus"],
    "c": ["c language", "ansi c"],
    "go": ["golang"],
    "rust": ["rust lang"],
    "kotlin": ["kotlin jvm"],
    "swift": ["swift 5"],
    "scala": ["scala 3", "apache scala"],
    "r": ["r language", "r stats", "r programming"],
    "matlab": ["mathworks matlab"],
    "php": ["php 8"],
    "ruby": ["ruby on rails", "ror"],
    "perl": [],
    "bash": ["shell script", "bash scripting", "sh"],
    "powershell": ["ps1", "pwsh"],
    "lua": [],
    "dart": ["flutter dart"],
    # ── Web Frameworks ───────────────────────────────────────
    "django": ["django rest framework", "drf"],
    "flask": ["flask api"],
    "fastapi": ["fast api"],
    "spring boot": ["springboot", "spring framework"],
    "asp.net": ["asp.net core", ".net core", "aspnet"],
    "express.js": ["expressjs", "express"],
    "next.js": ["nextjs"],
    "react": ["reactjs", "react.js"],
    "angular": ["angularjs", "angular 17"],
    "vue.js": ["vuejs", "vue"],
    "svelte": [],
    "nuxt.js": ["nuxtjs"],
    "laravel": [],
    "rails": ["ruby on rails", "ror"],
    # ── Data Engineering ─────────────────────────────────────
    "apache spark": ["spark", "pyspark"],
    "apache kafka": ["kafka", "confluent kafka"],
    "apache airflow": ["airflow"],
    "apache hadoop": ["hadoop", "hdfs", "mapreduce"],
    "apache flink": ["flink"],
    "apache beam": ["beam"],
    "apache hive": ["hive"],
    "dbt": ["data build tool", "dbt core", "dbt cloud"],
    "luigi": [],
    "prefect": ["prefect 2"],
    "dagster": [],
    "nifi": ["apache nifi"],
    # ── Databases ────────────────────────────────────────────
    "postgresql": ["postgres", "psql", "pg"],
    "mysql": ["mariadb", "mysql 8"],
    "sqlite": [],
    "sql server": ["mssql", "microsoft sql server", "t-sql", "tsql"],
    "oracle db": ["oracle database", "pl/sql", "plsql"],
    "mongodb": ["mongo", "mongoose"],
    "redis": ["redis cache"],
    "cassandra": ["apache cassandra"],
    "elasticsearch": ["elastic search", "opensearch"],
    "neo4j": ["graph database", "cypher"],
    "dynamodb": ["aws dynamodb"],
    "firestore": ["google firestore"],
    "snowflake": [],
    "bigquery": ["google bigquery", "bq"],
    "redshift": ["aws redshift"],
    "delta lake": ["delta"],
    "apache iceberg": ["iceberg"],
    # ── Cloud Platforms ──────────────────────────────────────
    "aws": ["amazon web services", "amazon aws"],
    "gcp": ["google cloud", "google cloud platform"],
    "azure": ["microsoft azure", "azure cloud"],
    "oracle cloud": ["oci"],
    "ibm cloud": [],
    "alibaba cloud": [],
    # ── Cloud Services ───────────────────────────────────────
    "aws s3": ["s3", "amazon s3"],
    "aws ec2": ["ec2", "amazon ec2"],
    "aws lambda": ["lambda functions"],
    "aws glue": ["glue etl"],
    "aws emr": ["emr"],
    "aws sagemaker": ["sagemaker"],
    "azure data factory": ["adf"],
    "azure synapse": ["synapse analytics"],
    "azure databricks": ["databricks"],
    "gcs": ["google cloud storage"],
    "cloud run": ["google cloud run"],
    "cloud functions": ["google cloud functions"],
    # ── DevOps & Infra ────────────────────────────────────────
    "docker": ["dockerfile", "docker compose", "docker-compose"],
    "kubernetes": ["k8s", "kubectl", "helm"],
    "terraform": ["tf", "hcl"],
    "ansible": [],
    "jenkins": [],
    "github actions": ["gh actions"],
    "gitlab ci": ["gitlab ci/cd"],
    "circleci": [],
    "argocd": ["argo cd"],
    "prometheus": [],
    "grafana": [],
    "datadog": [],
    # ── ML & AI ───────────────────────────────────────────────
    "machine learning": ["ml", "supervised learning", "unsupervised learning"],
    "deep learning": ["dl", "neural networks", "ann"],
    "natural language processing": ["nlp", "text mining", "text analytics"],
    "computer vision": ["cv", "image recognition", "object detection"],
    "tensorflow": ["tf", "tensorflow 2"],
    "pytorch": ["torch"],
    "scikit-learn": ["sklearn", "scikit learn"],
    "keras": [],
    "xgboost": ["xgb"],
    "lightgbm": ["lgbm"],
    "catboost": [],
    "hugging face": ["transformers", "huggingface"],
    "openai api": ["gpt api", "openai"],
    "langchain": ["lang chain"],
    "llm": ["large language model", "llms"],
    "rag": ["retrieval augmented generation"],
    "mlflow": [],
    "kubeflow": [],
    "feature store": ["feast", "hopsworks"],
    # ── Data Analysis & Visualisation ─────────────────────────
    "pandas": ["pd"],
    "numpy": ["np"],
    "scipy": [],
    "matplotlib": [],
    "seaborn": [],
    "plotly": ["plotly express", "plotly dash", "dash"],
    "tableau": [],
    "power bi": ["powerbi", "microsoft power bi"],
    "looker": ["looker studio", "data studio"],
    "apache superset": ["superset"],
    "excel": ["microsoft excel", "advanced excel"],
    "google sheets": [],
    # ── Streaming & Messaging ─────────────────────────────────
    "rabbitmq": ["rabbit mq"],
    "apache pulsar": ["pulsar"],
    "aws kinesis": ["kinesis"],
    "azure event hubs": ["event hubs"],
    "google pub/sub": ["pubsub"],
    # ── Security ──────────────────────────────────────────────
    "oauth2": ["oauth 2.0", "openid connect", "oidc"],
    "jwt": ["json web token"],
    "ssl/tls": ["ssl", "tls", "https"],
    "vault": ["hashicorp vault"],
    "siem": [],
    "penetration testing": ["pentest", "ethical hacking"],
    # ── Testing ───────────────────────────────────────────────
    "pytest": [],
    "unittest": ["python unittest"],
    "jest": [],
    "selenium": ["selenium webdriver"],
    "cypress": [],
    "playwright": [],
    "junit": [],
    "testng": [],
    # ── Soft / Process ────────────────────────────────────────
    "agile": ["scrum", "kanban", "sprint"],
    "jira": ["atlassian jira"],
    "confluence": [],
    "git": ["git flow", "gitflow"],
    "github": [],
    "gitlab": [],
    "bitbucket": [],
    "rest api": ["restful api", "rest"],
    "graphql": [],
    "grpc": [],
    "microservices": ["micro services", "microservice architecture"],
    "event-driven architecture": ["eda", "event driven"],
    "data lake": ["datalake"],
    "data warehouse": ["dwh", "data warehousing"],
    "etl": ["extract transform load", "elt"],
    "data modeling": ["dimensional modeling", "star schema", "snowflake schema"],
    "sql": ["structured query language", "advanced sql", "sql queries"],
    "nosql": ["non-relational database"],
    "linux": ["ubuntu", "centos", "debian", "unix"],
    "streamlit": [],
    "fastapi": ["fast api"],
    "pydantic": [],
    "celery": ["celery workers", "celery beat"],
    "websockets": ["websocket", "ws"],
    "grpc": ["protobuf", "protocol buffers"],
    "opentelemetry": ["otel", "open telemetry"],
    "data governance": ["data catalog", "data lineage"],
    "data quality": ["great expectations", "deequ", "soda"],
    "apache zeppelin": ["zeppelin"],
    "jupyter": ["jupyter notebook", "jupyterlab"],
    "google colab": ["colab"],
    "dask": [],
    "polars": [],
    "sqlalchemy": ["sql alchemy"],
    "alembic": [],
    "pyspark": ["spark python api"],
    "data pipeline": ["data pipelines", "batch pipeline", "streaming pipeline"],
    "ci/cd": ["continuous integration", "continuous delivery", "continuous deployment"],
    "infrastructure as code": ["iac"],
}
